// Code generated by Thrift Compiler (0.14.1). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"github.com/apache/thrift/lib/go/thrift"
	"channelservice"
)

var _ = channelservice.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  WebLoginResponse getWebLoginDisallowedUrl(WebLoginRequest webLoginRequest)")
  fmt.Fprintln(os.Stderr, "   getUpdatedChannelIds( channelIds)")
  fmt.Fprintln(os.Stderr, "  bool updateChannelSettings(ChannelSettings channelSettings)")
  fmt.Fprintln(os.Stderr, "  WebLoginResponse getReturnUrlWithRequestTokenForAutoLogin(WebLoginRequest webLoginRequest)")
  fmt.Fprintln(os.Stderr, "  ChannelToken approveChannelAndIssueChannelToken(string channelId)")
  fmt.Fprintln(os.Stderr, "  void updateChannelNotificationSetting( setting)")
  fmt.Fprintln(os.Stderr, "  ChannelDomains getCommonDomains(i64 lastSynced)")
  fmt.Fprintln(os.Stderr, "  ChannelSettings getChannelSettings()")
  fmt.Fprintln(os.Stderr, "  RequestTokenResponse issueRequestTokenWithAuthScheme(string channelId, string otpId,  authScheme, string returnUrl)")
  fmt.Fprintln(os.Stderr, "  ChannelToken issueChannelToken(string channelId)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := channelservice.NewChannelServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "getWebLoginDisallowedUrl":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetWebLoginDisallowedUrl requires 1 args")
      flag.Usage()
    }
    arg41 := flag.Arg(1)
    mbTrans42 := thrift.NewTMemoryBufferLen(len(arg41))
    defer mbTrans42.Close()
    _, err43 := mbTrans42.WriteString(arg41)
    if err43 != nil {
      Usage()
      return
    }
    factory44 := thrift.NewTJSONProtocolFactory()
    jsProt45 := factory44.GetProtocol(mbTrans42)
    argvalue0 := channelservice.NewWebLoginRequest()
    err46 := argvalue0.Read(context.Background(), jsProt45)
    if err46 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetWebLoginDisallowedUrl(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getUpdatedChannelIds":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetUpdatedChannelIds requires 1 args")
      flag.Usage()
    }
    arg47 := flag.Arg(1)
    mbTrans48 := thrift.NewTMemoryBufferLen(len(arg47))
    defer mbTrans48.Close()
    _, err49 := mbTrans48.WriteString(arg47)
    if err49 != nil { 
      Usage()
      return
    }
    factory50 := thrift.NewTJSONProtocolFactory()
    jsProt51 := factory50.GetProtocol(mbTrans48)
    containerStruct0 := channelservice.NewChannelServiceGetUpdatedChannelIdsArgs()
    err52 := containerStruct0.ReadField1(context.Background(), jsProt51)
    if err52 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.ChannelIds
    value0 := argvalue0
    fmt.Print(client.GetUpdatedChannelIds(context.Background(), value0))
    fmt.Print("\n")
    break
  case "updateChannelSettings":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "UpdateChannelSettings requires 1 args")
      flag.Usage()
    }
    arg53 := flag.Arg(1)
    mbTrans54 := thrift.NewTMemoryBufferLen(len(arg53))
    defer mbTrans54.Close()
    _, err55 := mbTrans54.WriteString(arg53)
    if err55 != nil {
      Usage()
      return
    }
    factory56 := thrift.NewTJSONProtocolFactory()
    jsProt57 := factory56.GetProtocol(mbTrans54)
    argvalue0 := channelservice.NewChannelSettings()
    err58 := argvalue0.Read(context.Background(), jsProt57)
    if err58 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.UpdateChannelSettings(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getReturnUrlWithRequestTokenForAutoLogin":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetReturnUrlWithRequestTokenForAutoLogin requires 1 args")
      flag.Usage()
    }
    arg59 := flag.Arg(1)
    mbTrans60 := thrift.NewTMemoryBufferLen(len(arg59))
    defer mbTrans60.Close()
    _, err61 := mbTrans60.WriteString(arg59)
    if err61 != nil {
      Usage()
      return
    }
    factory62 := thrift.NewTJSONProtocolFactory()
    jsProt63 := factory62.GetProtocol(mbTrans60)
    argvalue0 := channelservice.NewWebLoginRequest()
    err64 := argvalue0.Read(context.Background(), jsProt63)
    if err64 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetReturnUrlWithRequestTokenForAutoLogin(context.Background(), value0))
    fmt.Print("\n")
    break
  case "approveChannelAndIssueChannelToken":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "ApproveChannelAndIssueChannelToken requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.ApproveChannelAndIssueChannelToken(context.Background(), value0))
    fmt.Print("\n")
    break
  case "updateChannelNotificationSetting":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "UpdateChannelNotificationSetting requires 1 args")
      flag.Usage()
    }
    arg66 := flag.Arg(1)
    mbTrans67 := thrift.NewTMemoryBufferLen(len(arg66))
    defer mbTrans67.Close()
    _, err68 := mbTrans67.WriteString(arg66)
    if err68 != nil { 
      Usage()
      return
    }
    factory69 := thrift.NewTJSONProtocolFactory()
    jsProt70 := factory69.GetProtocol(mbTrans67)
    containerStruct0 := channelservice.NewChannelServiceUpdateChannelNotificationSettingArgs()
    err71 := containerStruct0.ReadField1(context.Background(), jsProt70)
    if err71 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Setting
    value0 := argvalue0
    fmt.Print(client.UpdateChannelNotificationSetting(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getCommonDomains":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetCommonDomains requires 1 args")
      flag.Usage()
    }
    argvalue0, err72 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err72 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetCommonDomains(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getChannelSettings":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetChannelSettings requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetChannelSettings(context.Background()))
    fmt.Print("\n")
    break
  case "issueRequestTokenWithAuthScheme":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "IssueRequestTokenWithAuthScheme requires 4 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    arg75 := flag.Arg(3)
    mbTrans76 := thrift.NewTMemoryBufferLen(len(arg75))
    defer mbTrans76.Close()
    _, err77 := mbTrans76.WriteString(arg75)
    if err77 != nil { 
      Usage()
      return
    }
    factory78 := thrift.NewTJSONProtocolFactory()
    jsProt79 := factory78.GetProtocol(mbTrans76)
    containerStruct2 := channelservice.NewChannelServiceIssueRequestTokenWithAuthSchemeArgs()
    err80 := containerStruct2.ReadField3(context.Background(), jsProt79)
    if err80 != nil {
      Usage()
      return
    }
    argvalue2 := containerStruct2.AuthScheme
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.IssueRequestTokenWithAuthScheme(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "issueChannelToken":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "IssueChannelToken requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.IssueChannelToken(context.Background(), value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
